const mainURL = "https://work.emucoach.com/SYS_EKS3/api/";
export const servicepointsURL = mainURL + "servicepoints/servicepoints";
export const movieReviewURL = mainURL + "movie/review";
export const digitaloceanURL = mainURL + "digitalocean/admin";
export const songLookupURL = mainURL + "song/search";
export const songBookmarkURL = mainURL + "song/bookmark";
export const loginURL = mainURL + "login";
export const signUpURL = mainURL + "register";
export const getUsersURL = mainURL + "admin/all";
export const deleteUsersURL = mainURL + "admin/delete";
export const getSongURL = mainURL + "song/user/all";
export const editUserURL = mainURL + "admin/edit"